[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/ibz/odj"

[workspace.dependencies]
odj-core = { path = "crates/odj-core" }
anyhow = "1.0.104"
blake3 = "1.8.7"
cpal = { version = "0.18.2", features = ["pipewire"] }
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
symphonia = { version = "0.6.1", features = ["all"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
